# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AuoGJX-HHdDyVcREewNXhaJo5Nhx3CbX
"""

# Commented out IPython magic to ensure Python compatibility.
#importing the necessary packages
import pandas as pd
from matplotlib import pyplot as plt
# %matplotlib inline

#reading the csv
df = pd.read_csv('insurance_data.csv')
df.head()

#plotting the csv
plt.scatter(df.age,df.bought_insurance,marker='+',color='red')

#train test splitting
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df[['age']], df.bought_insurance, test_size = 0.1)

x_train

x_test

y_train

y_test

#importing logistic regression module and training the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

#predicting the x_test
model.predict(x_test)

#knowing how much efficiently the code works
model.score(x_test, y_test)

#predicting the percentage of the yes or no for insurances
model.predict_proba(x_test)

#predicting for  a particular age group
model.predict([[25]])